apiVersion: v1
kind: Secret
metadata:
  name: nb-cert-automation-secrets
  namespace: nb-cert-automation

type: Opaque

stringData:
  LINODE_API_TOKEN: "your-linode-api-token"
  LINODE_V4_API_KEY: "your-linode-api-token"

  # AWS Route53
  AWS_ACCESS_KEY_ID: "your-aws-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-access-key"

  # Cloudflare
  CF_Token: "your-cloudflare-api-token"

  # Akamai Edge DNS
  AKAMAI_HOST: "your-akamai-host"
  AKAMAI_CLIENT_TOKEN: "your-akamai-client-token"
  AKAMAI_CLIENT_SECRET: "your-akamai-client-secret"
  AKAMAI_ACCESS_TOKEN: "your-akamai-access-token"
