apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nb-cert-automation-data
  namespace: nb-cert-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
